version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fred_postgres
    environment:
      POSTGRES_DB: fred_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fred_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: